/* Single source of truth for the portfolio shown across the website. */
window.playablesData = [
  { title: "World Solitaire", thumb: "optimized-thumbnails/playables/wordscapes-solitaire-tripledot.jpg", src: "playables/WordScapesSolitaire/index.html", engine: "Cocos", note: "Tripple Dot" },
  { title: "Bitcoin Miner V1", thumb: "optimized-thumbnails/playables/28.jpg", src: "playables/BitcoinMinerV2/index.html", engine: "Cocos", note: "Bitcoin Miner - Fumb Games" },
  { title: "Idle Mine - Cocos", thumb: "optimized-thumbnails/playables/21.jpg", src: "playables/IdleMine/Idle Mine Cocos.html", engine: "Cocos", note: "Idle Mine - Cocos" },
  { title: "Sniper Battle - HypeGames", thumb: "optimized-thumbnails/playables/sniper-hypegames.jpg", src: "playables/SniperEmma/index.html", engine: "Cocos", note: "Sniper Battle - HypeGames" },
  { title: "????? - ?????", thumb: "optimized-thumbnails/playables/nda-goodgame.jpg", src: "playables/NDAGoodGame/index.html", engine: "Cocos", note: "????? - ?????" },
  { title: "Angry Mining Concept", thumb: "optimized-thumbnails/playables/16.jpg", src: "playables/kitchen/index.html", engine: "Luna", note: "Idle Mine - Fumb Games" },
  { title: "Ball Challenge", thumb: "optimized-thumbnails/playables/17.jpg", src: "playables/BallBounce/Index.html", engine: "Luna", note: "Ball Bounce And Merge - Moone" },
  { title: "Crystal Craven", thumb: "optimized-thumbnails/playables/4.jpg", src: "playables/CrystalCraven/index.html", engine: "Luna", note: "Idle Mine - Fumb Games" },
  { title: "Animal Hunt - Choose Weopen - HypeGames", thumb: "optimized-thumbnails/playables/wild-boar-sniper-hunt.jpg", src: "playables/WildBoarSniperHunt/index.html", engine: "Cocos", note: "Animal Hunt - Choose Weopen - HypeGames" },
  { title: "Idle Mine - Cocos V2", thumb: "optimized-thumbnails/playables/27.jpg", src: "playables/IdleMine/idleMineCocosV2.html", engine: "Cocos", note: "Idle Mine - Fumb Games" },
  { title: "Bitcoin Empire - Infinite Click", thumb: "optimized-thumbnails/playables/23.jpg", src: "playables/BE/BE_PB_GAMEPLAY_EARN_INFINITECLICKVIDEO_V10_INT_APPLOVIN.html", engine: "Luna", note: "Bitcoin Empire - Fumb Games" },
  { title: "Bitcoin Empire - Typing Infinite", thumb: "optimized-thumbnails/playables/24.jpg", src: "playables/BE/Be_Typing INfinie.html", engine: "Luna", note: "Bitcoin Empire - Fumb Games" },
  { title: "Bitcoin Empire - Story", thumb: "optimized-thumbnails/playables/25.jpg", src: "playables/BE/Story playable.html", engine: "Luna", note: "Bitcoin Empire - Fumb Games" },
  { title: "Bitcoin Empire With Hook", thumb: "optimized-thumbnails/playables/26.jpg", src: "playables/BE/BE_AI/index.html", engine: "Luna", note: "Bitcoin Empire - Fumb Games" },
  { title: "Sniper Hunting - Variant 3", thumb: "optimized-thumbnails/playables/20.jpg", src: "playables/SniperHunting/index3.html", engine: "Cocos", note: "Sniper Hunting - HypeGames" },
  { title: "Block Blast", thumb: "optimized-thumbnails/playables/19.jpg", src: "playables/BlockBlast/index.html", engine: "Luna", note: "Bitcoin BlockBlast - Fumb Games" },
  { title: "Cat Hide and Seek", thumb: "optimized-thumbnails/playables/14.jpg", src: "playables/Cat/index.html", engine: "Luna", note: "Cat Hide and Seek - OZI Games" },
  { title: "Piggy Tetris", thumb: "optimized-thumbnails/playables/1.jpg", src: "playables/Piggy/index.html", engine: "Luna", note: "Idle Bitcoin Mine - FumbGames" },
  { title: "Hero Making Tycoon", thumb: "optimized-thumbnails/playables/10.jpg", src: "playables/HMT/index.html", engine: "Luna", note: "Hero Making Tycoon - TapNation" },
  { title: "Piggy Collect", thumb: "optimized-thumbnails/playables/5.jpg", src: "playables/PiggyCollect/index.html", engine: "Luna", note: "Bitcoin Miner - Fumb Games" },
  { title: "Doll Dress Up", thumb: "optimized-thumbnails/playables/8.jpg", src: "playables/DDU/index.html", engine: "Unity", note: "Doll Dress Up - TapNation" },
  { title: "Hide And Seek", thumb: "optimized-thumbnails/playables/11.jpg", src: "playables/HideSeek/index.html", engine: "Luna", note: "Hide and Seek - Ozi Games" },
  { title: "Pocket Monster Rush", thumb: "optimized-thumbnails/playables/13.jpg", src: "playables/PMR/index.html", engine: "Unity", note: "Pocket Monster Rush - Tapnation" },
  { title: "Robot Rat Killer", thumb: "optimized-thumbnails/playables/7.jpg", src: "playables/RobotRat/index.html", engine: "Luna", note: "Robot Rat Killer - TapNation" },
  { title: "Guess Their Answer", thumb: "optimized-thumbnails/playables/9.jpg", src: "playables/GTA/index.html", engine: "Unity", note: "Guess Their Answer - TapNation" },
  { title: "Hero Making Tycoon Dressing", thumb: "optimized-thumbnails/playables/12.jpg", src: "playables/HMT2/index.html", engine: "Unity", note: "Hero Making Tycoon - Tapnation" }
];

window.creativesData = [
  { title: "Idle Clicker - Custom", thumb: "optimized-thumbnails/creatives/41.jpg", video: "creatives/42.mp4", note: "Idle Mine - FumbGames" },
  { title: "Puzzle - Custom", thumb: "optimized-thumbnails/creatives/39.jpg", video: "creatives/40.mp4", note: "Blocks of Bitcoin-FumbGames" },
  { title: "Puzzle - Custom", thumb: "optimized-thumbnails/creatives/40.jpg", video: "creatives/41.mov", note: "Blocks of Bitcoin-FumbGames" },
  { title: "Idle - CustomGamePlay", thumb: "optimized-thumbnails/creatives/38.jpg", video: "creatives/39.mp4", note: "IdleMine-FumbGames" },
  { title: "Simulation - CustomGamePlay", thumb: "optimized-thumbnails/creatives/1.jpg", video: "creatives/1.mp4", note: "My Laundary Simulator - Ozi Games" },
  { title: "HCG - CustomGamePlay", thumb: "optimized-thumbnails/creatives/2.jpg", video: "creatives/2.mp4", note: "Idle Mine Craft - TapNation" },
  { title: "HCG - CustomGamePlay", thumb: "optimized-thumbnails/creatives/4.jpg", video: "creatives/4.mp4", note: "Parking Jam - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/6.jpg", video: "creatives/3.mp4", note: "Giant Rush - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/25.jpg", video: "creatives/26.mp4", note: "Shoe Paint 3d - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/26.jpg", video: "creatives/28.mp4", note: "Mine Craft - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/27.jpg", video: "creatives/29.mp4", note: "Mine Craft - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/28.jpg", video: "creatives/30.mp4", note: "Pocket Monster Rush- TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/29.jpg", video: "creatives/31.mp4", note: "Pocket Monster Rush - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/30.jpg", video: "creatives/32.mp4", note: "Hero Adventure- TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/31.jpg", video: "creatives/33.mp4", note: "Wizard Universe - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/32.jpg", video: "creatives/34.mp4", note: "CornHole - TapNation" },
  { title: "HCG - Custom Gameplay", thumb: "optimized-thumbnails/creatives/33.jpg", video: "creatives/35.mp4", note: "Giant Rush - TapNation" },
  { title: "Simulation - Custom Gameplay", thumb: "optimized-thumbnails/creatives/34.jpg", video: "creatives/36.mp4", note: "Army Train Simulator - Ozi Games" },
  { title: "Custom Gameplay", thumb: "optimized-thumbnails/creatives/35.jpg", video: "creatives/37.mp4", note: "No Wifi Games - Ozi Games" },
  { title: "Guess Thier Answer - Custom Gameplay", thumb: "optimized-thumbnails/creatives/36.jpg", video: "creatives/38.mp4", note: "Guess thier Answer TapNation" }
];
